apiVersion: v1
kind: Secret
metadata:
  name: gitops-token
type: Opaque
data:
  password: bGluZ2ppYW45OUB5ZWFoLm5ldA==
  username: UGFzc3cwcmQ5OQ==
#type: Opaque
#data:
#  username: djxj
#  password: Djxj201585
#获取Base64编码：
#  echo -n "djxj" | base64