apiVersion: rbac.authorization.k8s.io/v1  
kind: ClusterRoleBinding  
metadata:  
  name: dashboard-operator-cluster-admin-binding  
subjects:  
- name: default  
  kind: ServiceAccount  
roleRef:  
  name: dashboard-operator-cluster-admin  
  kind: ClusterRole